language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler:
      - gcc
      - clang
    addons:
      apt:
        packages:
          - g++-8
          - clang-7
          - ninja-build
          - libsdl2-dev
          - libsdl2-*-dev
          - libglm-dev

before_script:
  - cmake --version
  - ${CXX} --version

script:
  - mkdir build
  - cd build
  - cmake -GNinja ..
  - cmake --build .
